### ISSUE TITLE
integration type templates

### ISSUE THREAD

**Issue by doebrowsk** [Keyfactor/actions#1]
Enhancement on the basic readme_source.md

Instead of having a plain markdown inserted from the readme_source.md, we could set up templates for each integration_type. This way some readme structure between common integration types that could be generated and then appended to the end of the final readme (where readme_source goes now).

**Comment by fiddlermikey** [comment]
I started some work on another branch that will include integration_type-specific templates to be appended to the main readme file. https://github.com/Keyfactor/actions/tree/add-templates
It is unclear what the common language should look like and how the final page should be displayed.

**Comment by fiddlermikey** [comment]
A separate but comparable template enhancement was made to include platform specific information. This same technique can be used for any number of templates.
