### ISSUE TITLE
full release runs when PR goes to non-release branch with latest release commits

### ISSUE THREAD

**Issue by doebrowsk** [Keyfactor/actions#6]
A full release should only run on a `release-*` branch, but it can accidentally run on `main` or a feature branch.
This occurs when that branch has the latest commits from a just-released branch, as the head commit then matches the commit from the PR that created a release. When this is the case, that commit SHA matches the PR and a release can be created when a new PR into one of these branches (usually `main`) occurs, which appears to meet the criteria for a release.

There should be an additional check in the `merged_pull_request` step in the [github-release.yml workflow](https://github.com/Keyfactor/actions/blob/main/.github/workflows/github-release.yml). This check would make sure we are explicitly running on a `release-` branch and could be part of the `IS_RELEASE` flag.

**Comment by fiddlermikey** [comment]
I need to do some additional testing but I think it should be as simple as modifying line 83 to read:
const IS_RELEASE = (state == 'closed') && (mergeSHA == context.sha) && (pulls.data[0].base.ref.startswith == 'release-');

It might be easier to read by defining a const for targetBranchName = pulls.data[0].base.ref and then line 83 would read:
const IS_RELEASE = (state == 'closed') && (mergeSHA == context.sha) && (targetBranchName.startswith == 'release-');

**Comment by fiddlermikey** [comment]
I completed testing in a separate repository and found the code changes from the last comment will determine the branch being pushed to. A pr has been created #10 (https://github.com/Keyfactor/actions/pull/10) a review requested.

**Comment by fiddlermikey** [comment]
fixed https://github.com/Keyfactor/actions/pull/16
